### ISSUE TITLE
获取美股数据失败

### ISSUE THREAD

**Issue by dackon** [jindaxiang/akshare#1]
就这只美股"TEX"有问题，其他股票没发现问题

```python
df = ak.stock_us_daily(‘TEX’)
```

```terminal
Traceback (most recent call last):
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 1979, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/main.py", line 66, in <module>
    main()
  File "./src/main.py", line 61, in main
    st.update()
  File "/Users/foo/Workspace/pythonprj/stock/src/store.py", line 29, in update
    self.addStockData(c)
  File "/Users/foo/Workspace/pythonprj/stock/src/store.py", line 51, in addStockData
    arr = self.getStockData(c)
  File "/Users/foo/Workspace/pythonprj/stock/src/store.py", line 38, in getStockData
    df = ak.stock_us_daily(c)
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/akshare/stock/us_stock_sina.py", line 61, in stock_us_daily
    data_df.index = pd.to_datetime(data_df["date"])
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/pandas/util/_decorators.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 778, in to_datetime
    values = convert_listlike(arg._values, True, format)
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 456, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 1984, in objects_to_datetime64ns
    raise e
  File "/Users/foo/Workspace/pythonprj/stock/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 1969, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 465, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 683, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 679, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 654, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslibs/np_datetime.pyx", line 118, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 2703-01-16 00:00:00
```

**Comment by jindaxiang** [comment]
注意看黄色圆圈部分，这边应该是新浪网站的问题，他的时间是错误的
![DD4E2A9F-0BAD-4BBC-8E9E-C6CB814631E0](https://user-images.githubusercontent.com/18234520/69313527-c76c8280-0c6c-11ea-9e83-a19c4a749263.jpeg)

**Comment by jindaxiang** [comment]
已经给新浪提交资料，只能靠新浪在原始数据修正，感谢提供这么大的bug

**Comment by dackon** [comment]
Sina fixed.
