### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wangkaiX** [jindaxiang/akshare#1236]
ubuntu 20.04下
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>> stock_info_sz_df = ak.stock_info_sz_name_code(indicator="A股列表")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/akshare/stock/stock_info.py", line 32, in stock_info_sz_name_code
    temp_df = pd.read_excel(BytesIO(r.content), engine="xlrd")
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/excel/_base.py", line 1097, in __init__
    ext = inspect_excel_format(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/excel/_base.py", line 965, in inspect_excel_format
    raise ValueError("File is not a recognized excel file")
ValueError: File is not a recognized excel file
>>> ak.__version__
'0.9.14'
>>> import pandas
>>> pandas.__version__
'1.2.4'
>>>

**Comment by wangkaiX** [comment]
可能是我自己的问题，今天上午一直不行，下午似乎可以了
