### ISSUE TITLE
金十新闻数据处理错误

### ISSUE THREAD

**Issue by liulinlin90** [jindaxiang/akshare#1438]
金十新闻数据处理错误
```
Traceback (most recent call last):
  File "/home/ubuntu/akshare/js_news.py", line 43, in <module>
    run()
  File "/home/ubuntu/akshare/js_news.py", line 36, in run
    data = ak.js_news(indicator='最新资讯')
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/akshare/ws/js_ws_news.py", line 25, in js_news
    text_data = r.json()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jindaxiang** [comment]
> 金十新闻数据处理错误
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/akshare/js_news.py", line 43, in <module>
>     run()
>   File "/home/ubuntu/akshare/js_news.py", line 36, in run
>     data = ak.js_news(indicator='最新资讯')
>   File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/akshare/ws/js_ws_news.py", line 25, in js_news
>     text_data = r.json()
>   File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/requests/models.py", line 898, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
>     return _default_decoder.decode(s)
>   File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

感谢反馈问题，由于目标网站接口已经修改，已经修复该接口并做了一定参数修改，请升级到到 0.9.98 版本，并查看相关文档
