### ISSUE TITLE
获取两市停复牌数据，某些日期会出现数据解析出错

### ISSUE THREAD

**Issue by leesGb** [jindaxiang/akshare#384]
================ 2020-06-24
Traceback (most recent call last):
  File "h:/project/stock/new/src/data/collect/stock_out_date.py", line 47, in <module>
    stock_em_tfp_df = ak.stock_em_tfp(trade_date=day_str)
  File "C:\Users\lees\AppData\Roaming\Python\Python37\site-packages\akshare\stock_feature\stock_em_tfp.py", line 38, in stock_em_tfp
    temp_df = pd.DataFrame(data_json["data"]).iloc[:, 0].str.split(",", expand=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\strings.py", line 2041, in __init__
    self._inferred_dtype = self._validate(data)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\strings.py", line 2098, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!

获取2020-06-24这天的数据出错

**Comment by jindaxiang** [comment]
> ================ 2020-06-24
> Traceback (most recent call last):
> File "h:/project/stock/new/src/data/collect/stock_out_date.py", line 47, in
> stock_em_tfp_df = ak.stock_em_tfp(trade_date=day_str)
> File "C:\Users\lees\AppData\Roaming\Python\Python37\site-packages\akshare\stock_feature\stock_em_tfp.py", line 38, in stock_em_tfp
> temp_df = pd.DataFrame(data_json["data"]).iloc[:, 0].str.split(",", expand=True)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5270, in **getattr**
> return object.**getattribute**(self, name)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\accessor.py", line 187, in **get**
> accessor_obj = self._accessor(obj)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\strings.py", line 2041, in **init**
> self._inferred_dtype = self._validate(data)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\strings.py", line 2098, in _validate
> raise AttributeError("Can only use .str accessor with string values!")
> AttributeError: Can only use .str accessor with string values!
> 
> 获取2020-06-24这天的数据出错

经测试，可以正常获取 2020-06-24，建议升级 pandas 到最新版
