### ISSUE TITLE
epidemic_dxy crashes on national and regional queries

### ISSUE THREAD

**Issue by ericqianli** [jindaxiang/akshare#5]
epidemic_dxy crashes on indicator="全国" or indicator="浙江省" etc.

**Query**
`epidemic_dxy_df = ak.epidemic_dxy(indicator="全国")`
`print(epidemic_dxy_df)`

**Error**
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/event/sos.py", line 75, in epidemic_dxy
    data_df.columns = ["地区", "地区简称", "确诊", "疑似", "治愈", "死亡", "备注", "区域"]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 5286, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 177, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 9 elements, new values have 8 elements

Similarly:

**Query**
`epidemic_dxy_df = ak.epidemic_dxy(indicator="浙江省")`
`print(epidemic_dxy_df)`

**Error**
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/event/sos.py", line 75, in epidemic_dxy
    data_df.columns = ["地区", "地区简称", "确诊", "疑似", "治愈", "死亡", "备注", "区域"]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 5286, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 177, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 9 elements, new values have 8 elements

**Comment by jindaxiang** [comment]
Hello, this error had been fixed in version 0.3.70.
you can `pip install akshare --upgrade` to 0.3.70.
Thanks for your issuse

**Comment by ericqianli** [comment]
This is fixed in version 0.3.70. Thanks.
