### ISSUE TITLE
库存数据-东方财富 返回错误

### ISSUE THREAD

**Issue by congcong009** [jindaxiang/akshare#560]
版本 0.6.33

调用接口： ak.futures_inventory_em

返回结果：

> Traceback (most recent call last):
  File "########.py", line 11, in <module>
    df = pd.DataFrame(ak.futures_inventory_em(exchange="上海期货交易所", symbol="沪铜"))
  File "/Users/###/.conda/envs/###/lib/python3.7/site-packages/akshare/futures/futures_inventory_em.py", line 34, in futures_inventory_em
    temp_dict = demjson.decode(temp_text[temp_text.find('cv= ')+4:temp_text.rfind(';\r\n;')])
  File "/Users/###/.conda/envs/###/lib/python3.7/site-packages/demjson.py", line 5699, in decode
    return_stats=(return_stats or write_stats) )
  File "/Users/###/.conda/envs/###/lib/python3.7/site-packages/demjson.py", line 4915, in decode
    raise errors[0]
demjson.JSONDecodeError: No value to decode

**Comment by jindaxiang** [comment]
> ak.futures_inventory_em

感谢反馈问题，已修复该问题，请升级到 AkShare 0.6.34 版本

**Comment by TopGun666** [comment]
类似Bug
版本0.8.10 python 3.6.5或 3.7.9 其他未测试

调用接口： `zh_stock_kcb_sina.py`里`ak.stock_zh_kcb_daily`

```shell
Traceback (most recent call last):
  File "data_capture.py", line 18, in <module>
    main()
  File "data_capture.py", line 13, in main
    stock_zh_kcb_daily = ak.stock_zh_kcb_daily("sh000003")
  File "/Users/heyu/anaconda3/envs/py37/lib/python3.7/site-packages/akshare/stock/zh_stock_kcb_sina.py", line 96, in stock_zh_kcb_daily
    amount_data_json = demjson.decode(r.text[r.text.find("["): r.text.rfind("]")+1])
  File "/Users/heyu/anaconda3/envs/py37/lib/python3.7/site-packages/demjson.py", line 5699, in decode
    return_stats=(return_stats or write_stats) )
  File "/Users/heyu/anaconda3/envs/py37/lib/python3.7/site-packages/demjson.py", line 4915, in decode
    raise errors[0]
demjson.JSONDecodeError: No value to decode
```
