### ISSUE TITLE
ak.index_stock_cons('399639')

### ISSUE THREAD

**Issue by aEgoist** [jindaxiang/akshare#647]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6b8e7ab113df>", line 1, in <module>
    ak.index_stock_cons('399639')
  File "/opt/anaconda3/lib/python3.8/site-packages/akshare/index/index_cons.py", line 93, in index_stock_cons
    soup.find(attrs={"class": "table2"})
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by aEgoist** [comment]
this was due to request too frequently
