### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by WuXu-CN** [jindaxiang/akshare#698]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```python
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
**描述遇到的问题**
1. ubuntu 18.04.2
2. Python 版本
    python 3.6
3. AkShare 版本 
    akshare (0.6.10)
4. 接口的名称和代码
    import akshare as ak
5. 接口报错的截图或代码
    /usr/bin/python3.6 /home/wuxu/PycharmProjects/Trade/akLib.py
Traceback (most recent call last):
  File "/home/wuxu/PycharmProjects/Trade/akLib.py", line 1, in <module>
    import akshare as ak
  File "/home/wuxu/.local/lib/python3.6/site-packages/akshare/__init__.py", line 1096, in <module>
    from akshare.stock_feature.stock_a_pb import stock_a_pb
  File "/home/wuxu/.local/lib/python3.6/site-packages/akshare/stock_feature/stock_a_pb.py", line 318, in <module>
    token = js_functions.call("hex", datetime.now().date().isoformat()).lower()
  File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 159, in _extract_result
    ret = json.loads(output_last_line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```python
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. ubuntu 18.04.2
> 2. Python 版本
>    python 3.6
> 3. AkShare 版本
>    akshare (0.6.10)
> 4. 接口的名称和代码
>    import akshare as ak
> 5. 接口报错的截图或代码
>    /usr/bin/python3.6 /home/wuxu/PycharmProjects/Trade/akLib.py
>    Traceback (most recent call last):
>    File "/home/wuxu/PycharmProjects/Trade/akLib.py", line 1, in 
>    import akshare as ak
>    File "/home/wuxu/.local/lib/python3.6/site-packages/akshare/**init**.py", line 1096, in 
>    from akshare.stock_feature.stock_a_pb import stock_a_pb
>    File "/home/wuxu/.local/lib/python3.6/site-packages/akshare/stock_feature/stock_a_pb.py", line 318, in 
>    token = js_functions.call("hex", datetime.now().date().isoformat()).lower()
>    File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
>    return self._call(name, *args)
>    File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
>    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
>    File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
>    return self.exec_(code)
>    File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
>    return self._exec_(source)
>    File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
>    return self._extract_result(output)
>    File "/home/wuxu/.local/lib/python3.6/site-packages/execjs/_external_runtime.py", line 159, in _extract_result
>    ret = json.loads(output_last_line)
>    File "/usr/lib/python3.6/json/**init**.py", line 354, in loads
>    return _default_decoder.decode(s)
>    File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>    File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
>    raise JSONDecodeError("Expecting value", s, err.value) from None
>    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 6. 期望获得的正确结果

升级到最新版本，Python 版本大于3.7
