### ISSUE TITLE
return None when function gets nothing, but not Error

### ISSUE THREAD

**Issue by windblood** [jindaxiang/akshare#99]
I tried to get egg's inventory and spot box, and I get Error.
I guess that the functions get nothing. It would be better to return None under such circumstances.

``` python
get_inventory_data(3, 80)
```
> Traceback (most recent call last):
  File "C:\Users\2689\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-09f1eaccfc62>", line 1, in <module>
    jd_invent = ak.get_inventory_data(3, 80, plot=False)
  File "C:\Users\2689\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_inventory.py", line 72, in get_inventory_data
    exchange_name = soup.find_all("select")[0].find_all(attrs={"selected": "selected"})[0].get_text()
IndexError: list index out of range

``` python
box_office_spot()
```
> Traceback (most recent call last):
  File "C:\Users\2689\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-0305ad6d3610>", line 1, in <module>
    ak.box_office_spot()
  File "C:\Users\2689\AppData\Roaming\Python\Python37\site-packages\akshare\movie\movie_maoyan.py", line 53, in box_office_spot
    map_dict = get_map(text=text)
  File "C:\Users\2689\AppData\Roaming\Python\Python37\site-packages\akshare\movie\movie_maoyan.py", line 39, in get_map
    map_li = map(lambda x: str(int(x)), _classify.knn_predict(info))
  File "C:\Users\2689\AppData\Roaming\Python\Python37\site-packages\akshare\movie\movie_maoyan_knn_font.py", line 43, in knn_predict
    np.zeros((df.shape[0], self.len - df.shape[1])),
ValueError: negative dimensions are not allowed

**Comment by jindaxiang** [comment]
Hello, i have checked the errors.
1. if you want to use function: get_inventory_data(3, 80), please put the function in try except, just like the example in source code, because of the website of is not worked vary well:
```
    for i in range(10):
        try:
            data = get_inventory_data(exchange=3, symbol=80, plot=True)
            print(data)
            break
        except:
            continue
```
2. box_office_spot function must use machine learning method e.g. KNN, it may found errors, so just try again, it will work again.

**Comment by windblood** [comment]
> Hello, i have checked the errors.
> 
> 1. if you want to use function: get_inventory_data(3, 80), please put the function in try except, just like the example in source code, because of the website of is not worked vary well:
> 
> ```
>     for i in range(10):
>         try:
>             data = get_inventory_data(exchange=3, symbol=80, plot=True)
>             print(data)
>             break
>         except:
>             continue
> ```
> 
> 1. box_office_spot function must use machine learning method e.g. KNN, it may found errors, so just try again, it will work again.

I tried again and both worked.
well, uncertain behavior is not a good experience. A nice project anyway
